### ISSUE TITLE
JavaFX java.lang.NullPointerException: Input stream must not be null

### ISSUE THREAD

**Issue by JordanChua** [nus-cs2103-AY2223S1/forum#120]
Hi I have been following the steps as stated in implementing the GUI but when running my launcher class I get a nullPointer Exception, which i suspect may be due to some problem in the directory I have input in the specific lines: 

As per the error message it appears that in this particular part of MainWindow.fxml: 
`
xmlns="http://javafx.com/javafx/8.0.171" xmlns:fx="http://javafx.com/fxml/1"
`
Intellij gives the warning that these 2 URL are not supported.

Any help or ideas on what could be wrong would be appreciated :) Here is the link to my current branch if its easier to see: 
[branch-level-10](https://github.com/JordanChua/ip/tree/branch-Level-10)

```java
javafx.fxml.LoadException: 
/C:/Users/jcyx1/OneDrive/Documents/GitHub/ip/build/resources/main/view/MainWindow.fxml:9

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2625)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2603)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
	at duke.Main.start(Main.java:26)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.NullPointerException: Input stream must not be null
	at javafx.scene.image.Image.validateInputStream(Image.java:1117)
	at javafx.scene.image.Image.<init>(Image.java:701)
	at duke.MainWindow.<init>(MainWindow.java:27)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Caused by: java.lang.NullPointerException: Input stream must not be null
```

:bulb: You can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format your text

**Comment by malwaregarry** [comment]
Hi, can you upload your `build.gradle` file?

**Comment by JordanChua** [comment]
Sure this is my build.gradle file: 
`
plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '5.1.0'
}

repositories {
    mavenCentral()
}
    test {
        useJUnitPlatform()
    }

    dependencies {
        String javaFxVersion = '11'

        implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
        implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
        implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
        implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
        implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
        implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
        implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
        implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
        implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
        implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
        implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
        implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
        testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.5.0'
        testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.5.0'
    }

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClassName = "seedu.duke.Duke"
}

shadowJar {
    archiveBaseName = "duke"
    archiveClassifier = null
}

run{
    standardInput = System.in
}

`

**Comment by JordanChua** [comment]
Sure this is the code for my build.gradle file: 
[build.gradle.txt](https://github.com/nus-cs2103-AY2223S1/forum/files/9468485/build.gradle.txt)

**Comment by kxrt** [comment]
Hi, could you push the current contents of your branch to GitHub?

**Comment by JordanChua** [comment]
Sure I have pushed my current changes to my branch and I have attached the link to it in my orginal post as well :)

**Comment by malwaregarry** [comment]
Hi @JordanChua, your images are in `jpg` not `png`.

**Comment by JordanChua** [comment]
I changed my images to png format and it worked! Thank you for the help! 👍
