### ISSUE TITLE
Unable to open DISPLAY on WSL2 after adding Gui

### ISSUE THREAD

**Issue by misterpuffin** [nus-cs2103-AY2223S1/forum#150]
Hi everyone, I was trying to add JavaFX to my Duke application. However, after following the tutorial I was unable to run my app with ```./gradlew clean run``` I suspect it might be an issue with my WSL2 installation, as I am using the jdk stored in my WSL2.

Here is the error message I got.

```
> Task :run FAILED
Authorization required, but no authorization protocol specified
Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:173)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:171)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
        at com.sun.glass.ui.Application.run(Application.java:144)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:258)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:829)

FAILURE: Build failed with an exception.

```

* Your development environment (IntelliJ version, Java version, OS, ...)
```
openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

**Comment by zupey** [comment]
Hi misterpuffin,

I have faced a similar issue when setting up the GUI for my Duke.
This is the stackoverflow [page](https://stackoverflow.com/questions/69171337/javafx-error-in-wsl-2-java-lang-unsupportedoperationexception-unable-to-open) that I referenced. I followed the guide from the 0 upvote post to setup an X server on wsl.

All the best for your GUI. 😄

**Comment by RussellDash332** [comment]
See #118. Hope it helps!

**Comment by misterpuffin** [comment]
thanks everyone for the help! I ended up follow @zupey's advice and managed to get it working :)

closing the thread for now!

**Comment by damithc** [comment]
In case someone else comes to this thread, the other (simpler) solution is to not use WSL when running the application. Other options such as the regular CMD shell or the PowerShell will not have this problem.
