### ISSUE TITLE
Request for help of smoke test on Windows/Linux

### ISSUE THREAD

**Issue by bokun2** [nus-cs2103-AY2223S1/forum#227]
Here is my [application](https://github.com/bokun2/ip/releases) and my [User Guide](https://bokun2.github.io/ip/) and I would appreciate some Smoke-Test on Windows/Linux. Thank you for helping!

Edit: I have updated the jar file. Thanks again for any tests >_<

**Comment by cheeheng** [comment]
I would like to help but it appears that you forgot to upload the binary file on the Release section.

Update: I have tested on Windows 11 and the jar file seems to be working.

**Comment by JasonYapzx** [comment]
Hey, I tested with the file in your build folder and it works for Windows 10, just remember to upload the release file before the deadline.
![image](https://user-images.githubusercontent.com/63844743/190654273-b8ae95d3-dbe8-4620-88ce-fb30a4df199f.png)

**Comment by bokun2** [comment]
> I would like to help but it appears that you forgot to upload the binary file on the Release section.
> 
> Update: I have tested on Windows 11 and the jar file seems to be working.

Hi I have updated the binary file. Could you pls help to see if it works? Thanks!

**Comment by bokun2** [comment]
> Hey, I tested with the file in your build folder and it works for Windows 10, just remember to upload the release file before the deadline.
> ![image](https://user-images.githubusercontent.com/63844743/190654273-b8ae95d3-dbe8-4620-88ce-fb30a4df199f.png)

Hi I have updated the binary file. Could you pls help to see if the file works? Thanks!

**Comment by JasonYapzx** [comment]
> > Hey, I tested with the file in your build folder and it works for Windows 10, just remember to upload the release file before the deadline.
> > ![image](https://user-images.githubusercontent.com/63844743/190654273-b8ae95d3-dbe8-4620-88ce-fb30a4df199f.png)
> 
> Hi I have updated the binary file. Could you pls help to see if the file works? Thanks!

I have tested it again and yes it does work. Hope this helps :) 👍🏻

**Comment by bokun2** [comment]
> > > Hey, I tested with the file in your build folder and it works for Windows 10, just remember to upload the release file before the deadline.
> > > ![image](https://user-images.githubusercontent.com/63844743/190654273-b8ae95d3-dbe8-4620-88ce-fb30a4df199f.png)
> > 
> > 
> > Hi I have updated the binary file. Could you pls help to see if the file works? Thanks!
> 
> I have tested it again and yes it does work. Hope this helps :) 👍🏻

Thanks!!

**Comment by RezwanArefin01** [comment]
I got a completely blank screen on Linux (Arch): 
![Screenshot_20220917_013548](https://user-images.githubusercontent.com/22095441/190699369-7165236c-a99a-4ba2-b3cc-12cbf1b54d10.png)
And it also gets into an infinite loop of printing exceptions:
```
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Image must be non-null
        at com.sun.prism.paint.ImagePattern.<init>(ImagePattern.java:44)
        at com.sun.javafx.tk.quantum.QuantumToolkit.createImagePatternPaint(QuantumToolkit.java:924)
        at com.sun.javafx.tk.Toolkit.getPaint(Toolkit.java:661)
        at javafx.scene.paint.ImagePattern.acc_getPlatformPaint(ImagePattern.java:292)
        at javafx.scene.paint.Paint$1.getPlatformPaint(Paint.java:48)
        at javafx.scene.shape.Shape.updatePGShape(Shape.java:963)
        at javafx.scene.shape.Shape.doUpdatePeer(Shape.java:998)
        at javafx.scene.shape.Shape.access$000(Shape.java:123)
        at javafx.scene.shape.Shape$1.doUpdatePeer(Shape.java:131)
        at com.sun.javafx.scene.shape.ShapeHelper.updatePeerImpl(ShapeHelper.java:74)
        at com.sun.javafx.scene.shape.CircleHelper.updatePeerImpl(CircleHelper.java:64)
        at com.sun.javafx.scene.NodeHelper.updatePeer(NodeHelper.java:102)
        at javafx.scene.Node.syncPeer(Node.java:710)
        at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2380)
        at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
        at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
        at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
        at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
        at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
        at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
        at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
        at javafx.scene.Scene$ScenePulseListener.synchronizeSceneNodes(Scene.java:2356)
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2512)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
Keeps printing this non stop.
[This thread](https://github.com/nus-cs2103-AY2223S1/forum/issues/217) might be related.

**Comment by bokun2** [comment]
> I got a completely blank screen on Linux (Arch): ![Screenshot_20220917_013548](https://user-images.githubusercontent.com/22095441/190699369-7165236c-a99a-4ba2-b3cc-12cbf1b54d10.png) And it also gets into an infinite loop of printing exceptions:
> 
> ```
> Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Image must be non-null
>         at com.sun.prism.paint.ImagePattern.<init>(ImagePattern.java:44)
>         at com.sun.javafx.tk.quantum.QuantumToolkit.createImagePatternPaint(QuantumToolkit.java:924)
>         at com.sun.javafx.tk.Toolkit.getPaint(Toolkit.java:661)
>         at javafx.scene.paint.ImagePattern.acc_getPlatformPaint(ImagePattern.java:292)
>         at javafx.scene.paint.Paint$1.getPlatformPaint(Paint.java:48)
>         at javafx.scene.shape.Shape.updatePGShape(Shape.java:963)
>         at javafx.scene.shape.Shape.doUpdatePeer(Shape.java:998)
>         at javafx.scene.shape.Shape.access$000(Shape.java:123)
>         at javafx.scene.shape.Shape$1.doUpdatePeer(Shape.java:131)
>         at com.sun.javafx.scene.shape.ShapeHelper.updatePeerImpl(ShapeHelper.java:74)
>         at com.sun.javafx.scene.shape.CircleHelper.updatePeerImpl(CircleHelper.java:64)
>         at com.sun.javafx.scene.NodeHelper.updatePeer(NodeHelper.java:102)
>         at javafx.scene.Node.syncPeer(Node.java:710)
>         at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2380)
>         at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
>         at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
>         at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
>         at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
>         at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
>         at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
>         at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
>         at javafx.scene.Scene$ScenePulseListener.synchronizeSceneNodes(Scene.java:2356)
>         at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2512)
>         at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
>         at java.base/java.security.AccessController.doPrivileged(Native Method)
>         at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
>         at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
>         at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
>         at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
>         at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
>         at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
>         at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
>         at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
>         at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
>         at java.base/java.lang.Thread.run(Thread.java:829)
> ```
> 
> Keeps printing this non stop. [This thread](https://github.com/nus-cs2103-AY2223S1/forum/issues/217) might be related.

Hi I have uploaded another [version](https://github.com/bokun2/ip/releases). Could you pls see if it works? Thanks

**Comment by zhongfu** [comment]
seems to work fine now (Linux, sway), though force-resizing the app breaks the layout a little 

![image](https://user-images.githubusercontent.com/1695582/190890374-746d4d1b-2885-4b40-bd70-b8876480a6a6.png)
