### ISSUE TITLE
Request for smoke testing help (Linux)

### ISSUE THREAD

**Issue by bryanngzh** [nus-cs2103-AY2223S1/forum#228]
Hi! Would appreciate it if anybody could help me test my JAR file on Linux.
My jar file can be found [here](https://github.com/bryanngzh/ip/releases/tag/A-Release) and my UG [here](https://bryanngzh.github.io/ip/).

Thanks!

**Comment by RezwanArefin01** [comment]
On Linux (Arch) it gets into an infinite loop of printing exceptions: 
```
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Image must be non-null
        at com.sun.prism.paint.ImagePattern.<init>(ImagePattern.java:44)
        at com.sun.javafx.tk.quantum.QuantumToolkit.createImagePatternPaint(QuantumToolkit.java:924)
        at com.sun.javafx.tk.Toolkit.getPaint(Toolkit.java:661)
        at javafx.scene.paint.ImagePattern.acc_getPlatformPaint(ImagePattern.java:292)
        at javafx.scene.paint.Paint$1.getPlatformPaint(Paint.java:48)
        at javafx.scene.shape.Shape.updatePGShape(Shape.java:963)
        at javafx.scene.shape.Shape.doUpdatePeer(Shape.java:998)
        at javafx.scene.shape.Shape.access$000(Shape.java:123)
        at javafx.scene.shape.Shape$1.doUpdatePeer(Shape.java:131)
        at com.sun.javafx.scene.shape.ShapeHelper.updatePeerImpl(ShapeHelper.java:74)
        at com.sun.javafx.scene.shape.CircleHelper.updatePeerImpl(CircleHelper.java:64)
        at com.sun.javafx.scene.NodeHelper.updatePeer(NodeHelper.java:102)
        at javafx.scene.Node.syncPeer(Node.java:710)
        at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2380)
        at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
        at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
        at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
        at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
        at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
        at javafx.scene.Scene$ScenePulseListener.syncAll(Scene.java:2389)
        at javafx.scene.Scene$ScenePulseListener.synchronizeSceneNodes(Scene.java:2356)
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2512)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by bryanngzh** [comment]
Hi, I've changed the image type from jpeg to png, hopefully, that fixes the issue!
I would appreciate it if anyone could help me retest this on Linux.
I've updated the jar file above.
(Also, if anyone has any insights on how to fix the above do let me know)

Thanks!
