### ISSUE TITLE
Error: A JNI error has occurred, please check your installation and try again

### ISSUE THREAD

**Issue by shawnkai** [nus-cs2103-AY2223S1/forum#23]
I was attempting A-TextUiTesting when I ran into the error of 

cmd.exe /c runtest.bat
********** BUILD FAILURE ************
'javac' is not recognized as an internal or external command,
operable program or batch file.

I tried to follow the instructions but I'm not sure if I gave the correct location of java for JAVA_HOME. The location I gave was 
C:\Users\tanji\.jdks\corretto-11.0.16 which is the language I'm using for the project now. Now this is what I get when I try to run the  runtest.bat file: 

`cmd.exe /c runtest.bat
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Duke has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)`

not sure if a screenshot of the environment variables page would help too 
![image](https://user-images.githubusercontent.com/70712915/185306578-1292f463-7d7d-4e2b-a95d-70d3b6560f22.png)

Thank you in advance!

**Comment by shawnkai** [comment]
Not sure why the indentations didnt work when I was giving the error code. This is just to make it clearer:

cmd.exe /c runtest.bat
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Duke has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by damithc** [comment]
@shawnkai note that you need to restart Intellij (or the command terminal) after updating the PATH for it to use the updated PATH.

**Comment by shawnkai** [comment]
@damithc I have already tried restarting Intellij

**Comment by damithc** [comment]
Other things to try: 
* In your terminal used for running the batch file, run `java -version` and `javac -version` to verify Java 11 is being used.
* If you have Java 8 in your computer and don't need it for anything else, uninstall it. 
* Delete any .class files you already have (which could have been compiled using a different version of Java)

**Comment by shawnkai** [comment]
Hi Prof, I keyed in java -version and got 
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)

may i know how to change to java 11 and delete java 8? When I checked the project structure, it indicates I'm using java 11 so I'm slightly confused.

![image](https://user-images.githubusercontent.com/70712915/185337805-2392c690-fa34-42ac-a25b-e4cd65601731.png)

**Comment by damithc** [comment]
@shawnkai Looks like your tests are using Java 8. If you are running a batch file inside Intellij, it's still running in a terminal environment such as PowerShell or Windows Terminal (although it appears inside Intellij) The terminal is not affected by Intellij settings. Instead, it follows system settings of the OS. So, you need to set your Windows PATH variable to point to Java 11 `bin` directory. If Java 8 is already in the PATH, remove it.
![image](https://user-images.githubusercontent.com/1673303/185342246-14bb0843-9fd4-4f48-92d3-fae880418f89.png)
I suspect the part in the red box is what causes Java 8 to be used. As I mentioned, if you don't need Java 8 for anything, it's cleaner to just uninstall it.

**Comment by shawnkai** [comment]
The issue has been resolved. Thank you!
