### ISSUE TITLE
Request smoke test for Linux/ MacOS system 

### ISSUE THREAD

**Issue by xhphoong** [nus-cs2103-AY2223S1/forum#234]
Hi , would appreciate if anyone can help me test my new version of [jar](https://github.com/xhphoong/ip/releases/tag/A-Release) for linux, MacOS, windows(just in case) ? and here is my [user guide](https://xhphoong.github.io/ip/). Thanks a lot !!!

**Comment by yuehernkang** [comment]
Hi @xhphoong it seems like the link does not have a jar file

**Comment by xhphoong** [comment]
I updated the link, can try see is it there? Thanks

**Comment by cheeheng** [comment]
I have found the binary file in the link. Anya works fine on Windows 11, although an exception is thrown on this particular input: ```mark node as visited```.

<img width="302" alt="image" src="https://user-images.githubusercontent.com/13196670/190683267-4e0a74f9-3f4d-4ace-ad3b-3591cd78a06a.png">

**Comment by RezwanArefin01** [comment]
Tested on Linux (Arch). When I first ran it, it threw me this: 
```
Exception in Application constructor
Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class anya.Main
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:890)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:802)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        ... 1 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at anya.Storage.readTask(Storage.java:78)
        at anya.Storage.readFile(Storage.java:70)
        at anya.Anya.<init>(Anya.java:27)
        at anya.Main.<init>(Main.java:22)
        ... 13 more
```
Turns out that I had a `data/duke.txt` in the directory from previous testing, containing their saved data. But Anya seems to have the same name for the data file. So it failed to handle the datafile corruption... The contents of the datafile were: 
```
T|0|Return Book
D|0|Submit iP|2022-12-15
```
Maybe try with this to debug the data loading. It is having some array out of bound somewhere.

After removing the file it works as expected. However, I'd suggest you to turn of screen resizeability by `stage.setResizeable(false)`. 
![Screenshot_20220917_015203](https://user-images.githubusercontent.com/22095441/190702023-e93265d0-60bc-43ac-99a1-1dc3be2dd534.png)

**Comment by xhphoong** [comment]
@cheeheng Thanks for catching the exception. I have update a new version of it [jar](https://github.com/xhphoong/ip/releases/tag/A-Release). Can help to check again? especially because there is supposed to be other words in the ",,," section. I tried in my computer and it shows it up so I also not sure.... Thank you!!

**Comment by xhphoong** [comment]
@RezwanArefin01  noted, thank you! and for the data loading, I think its because i use " : " to parse instead of "|" and after that I read it without checking whether the string array produced, thus causing array out of bounds. This is my updated [jar](https://github.com/xhphoong/ip/releases/tag/A-Release), maybe can recheck? Thank you!

**Comment by RezwanArefin01** [comment]
@xhphoong I think it is still not fixed; I still got the exception thrown. You can test it locally too: create a data/anya.txt file with the contents that I gave above. Then run Anya.
Possible fix: before [this line](https://github.com/xhphoong/ip/blob/master/src/main/java/Storage.java#L77), check for the array length and throw an exception.

**Comment by xhphoong** [comment]
@RezwanArefin01 @yeehaoo @johnbenedictyan Hi, I think I fix the problem alrdy, but can help me check again whether it works in linux /macs ? Thank you! The jar file is [here](https://github.com/xhphoong/ip/releases/tag/A-Release) and the [user guide](https://xhphoong.github.io/ip/). Thank you!

**Comment by ou4jairmeiogusrjejiepr** [comment]
> @RezwanArefin01 @yeehaoo @johnbenedictyan Hi, I think I fix the problem alrdy, but can help me check again whether it works in linux /macs ? Thank you! The jar file is [here](https://github.com/xhphoong/ip/releases/tag/A-Release) and the [user guide](https://xhphoong.github.io/ip/). Thank you!

works fine on my side! (fedora linux)
