### ISSUE TITLE
Request for smoke test on Linux and Mac

### ISSUE THREAD

**Issue by ChongCheeKaiClarence** [nus-cs2103-AY2223S1/forum#276]
Need help with testing. Thanks, Here is my [release](https://github.com/ChongCheeKaiClarence/ip/releases/tag/A-Release)

**Comment by t1mzzz** [comment]
Works okay for me. However, resizing doesn't work properly. You can disable it by using `stage.setResizable(false)`.
<img width="297" alt="image" src="https://user-images.githubusercontent.com/97350034/191324325-60c7706c-15d4-4447-9353-8782d969cbc0.png">

**Comment by Yongbeom-Kim** [comment]
Testing on Ubuntu WSL:

Your app suffers from https://github.com/nus-cs2103-AY2223S1/forum/issues/246 - please fix

When the app is resized, the text on the button is not responsive: 
![image](https://user-images.githubusercontent.com/63487502/191428445-e76702b3-765e-407a-96ee-41541a0f7661.png)

File IO works.

**Comment by ChongCheeKaiClarence** [comment]
@Yongbeom-Kim Thanks for the help! I disabled resizing, not sure if that is causing the bug. I tried fixing the issue from the link you sent. Could you help me to check?

**Comment by yuehernkang** [comment]
Hello @ChongCheeKaiClarence, this is how it runs on my macos, not sure if it is just  issues with my machine.

`Exception in Application constructor
Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class duke.Main
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:891)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:803)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.RuntimeException: Error! Task not given.
	at duke.Duke.<init>(Duke.java:33)
	at duke.Main.<init>(Main.java:16)
`

**Comment by ChongCheeKaiClarence** [comment]
@yuehernkang I realized I made the mistake of not putting the JavaFX block above the dependencies block.
Could you try it again? Thanks for the help!

**Comment by ChongCheeKaiClarence** [comment]
@t1mzzz Thanks for the help! I disabled the resizing.

**Comment by Yongbeom-Kim** [comment]
@ChongCheeKaiClarence app works now!
