### ISSUE TITLE
Request for smoke test help (MacOS, Linux)

### ISSUE THREAD

**Issue by nopehax** [nus-cs2103-AY2223S1/forum#293]
Hi guys, I've received an email from the teaching team stating that the following errors has been found during their automated smoke test:
```
On Linux, using Java 11, for the doomba.jar uploaded on 09-16-2022 (MM-DD-YYYY) at 14:58:52:
Graphics Device initialization failed for : es2, sw Error initializing QuantumRenderer: no suitable pipeline found 
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found at 
com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280) at 
com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222) at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260) at 
com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267) at 
com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158) at 
com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658) at 
com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678) at 
com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195) at 
java.base/java.lang.Thread.run(Thread.java:829) Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no 
suitable pipeline found at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94) at 
com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124) ... 1 more Exception in thread "main"
 java.lang.RuntimeException: No toolkit found at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272) at 
com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267) at 
com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158) at 
com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658) at 
com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678) at 
com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195) at 
java.base/java.lang.Thread.run(Thread.java:829) 


On Mac, using Java 11, for the doomba.jar uploaded on 09-16-2022 (MM-DD-YYYY) at 14:58:52:
Graphics Device initialization failed for : es2, sw Error initializing QuantumRenderer: no suitable pipeline found 
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found at 
com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280) at 
com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222) at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260) at 
com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267) at 
com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158) at 
com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658) at 
com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678) at 
com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195) at 
java.base/java.lang.Thread.run(Thread.java:834) Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no 
suitable pipeline found at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94) at 
com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124) ... 1 more Exception in thread "main" 
java.lang.RuntimeException: No toolkit found at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272) at 
com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267) at 
com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158) at 
com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658) at 
com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678) at 
com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195) at 
java.base/java.lang.Thread.run(Thread.java:834)

```

For my previous build, I followed the guide that was linked [here](https://openjfx.io/openjfx-docs/#gradle) instead of doing the copy and pasting way. It passed the Java CI checks with no errors, as shown in the screenshot below and I have also asked my friend who is using MacOS to test the jar file and it works. So I am not sure why it didn't pass the smoke test.
![image](https://user-images.githubusercontent.com/57407346/191348797-12dcbd50-26d0-4888-8771-588570edeccc.png)

But I've modified the code such that it uses the copy and paste way so could someone help me test out both of my code?
The original jar file can be found [here](https://github.com/nopehax/ip/releases/tag/Bug-Fix) and the one with the fix [here](https://github.com/nopehax/ip/releases/tag/A-BetterGui)

**Comment by Yongbeom-Kim** [comment]
I am on Ubuntu 20.04.5 WSL, and i am unable to run your app.

Stack trace:
```
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        ... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
Here is my specs:
```
dernbu@MSI:/mnt/c/users/Dernbu/Downloads/CS2103 Testing$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
Java version:
```
dernbu@MSI:/mnt/c/users/Dernbu/Downloads/CS2103 Testing$ java --version
java 18.0.2.1 2022-08-18
Java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)
```

So [this](https://stackoverflow.com/questions/21185156/javafx-on-linux-is-showing-a-graphics-device-initialization-failed-for-es2-s) thread asks you to run with the `-Dprism.verbose=true` flag, and here it is:
```
dernbu@MSI:/mnt/c/users/Dernbu/Downloads/CS2103 Testing$ java -Dprism.verbose=true -jar doomba.jar
Prism pipeline init order: es2 sw
Using Double Precision Marlin Rasterizer
Using dirty region optimizations
Not using texture mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
Prism pipeline name = com.sun.prism.es2.ES2Pipeline
GraphicsPipeline.createPipeline failed for com.sun.prism.es2.ES2Pipeline
java.lang.ClassNotFoundException: com.sun.prism.es2.ES2Pipeline
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:383)
        at java.base/java.lang.Class.forName(Class.java:376)
        at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:187)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        at java.base/java.lang.Thread.run(Thread.java:833)
*** Fallback to Prism SW pipeline
Prism pipeline name = com.sun.prism.sw.SWPipeline
GraphicsPipeline.createPipeline failed for com.sun.prism.sw.SWPipeline
java.lang.UnsatisfiedLinkError: no prism_sw in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
        at java.base/java.lang.System.loadLibrary(System.java:2015)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:150)
        at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:52)
        at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:42)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:41)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:383)
        at java.base/java.lang.Class.forName(Class.java:376)
        at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:187)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        at java.base/java.lang.Thread.run(Thread.java:833)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        ... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
I hope this helps in your troubleshooting, perhaps there is some dependency not captured somewhere? LMK if you need me to run anything else

**Comment by nopehax** [comment]
Ok, thanks for testing it out!

**Comment by damithc** [comment]
> For my previous build, I followed the guide that was linked [here](https://openjfx.io/openjfx-docs/#gradle) instead of doing the copy and pasting way. It passed the Java CI checks with no errors, as shown in the screenshot below and I have also asked my friend who is using MacOS to test the jar file and it works. So I am not sure why it didn't pass the smoke test.
> ![image](https://user-images.githubusercontent.com/57407346/191348797-12dcbd50-26d0-4888-8771-588570edeccc.png)

@nopehax CI tests are not using the JAR file. Hence, CI will not be able to detect problems related to the JAR file.

**Comment by nopehax** [comment]
Ah, I see thank you!
I found the problem, which was the circle component for JavaFX. Not sure why it was working for windows but not for macos and linux. I have removed the component and went back to using ImageView.
