### ISSUE TITLE
💡 Running tests while doing A-Packages - javac command in runtest.bat needs to be changed

### ISSUE THREAD

**Issue by clarence-chew** [nus-cs2103-AY2223S1/forum#42]
I tried moving my code into packages and the runtest.bat regression tests seem to fail. Running my code in IntelliJ looks pretty fine, so my initial guess is that the runtest.bat can't deal with packages.

I had all my classes in the packages `duke` and `duke.task`. As such, what I did was to change originally:

`javac  -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\*.java`

to:
`javac  -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\duke\*.java ..\src\main\java\duke\task\*.java`

Windows Powershell (if you use Windows, you might get an error like this):
```
PS C:\Users\[REMOVED]\nus-cs2103-AY2223S1-ip\text-ui-test> ./runtest.bat
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <*> at index 17: ..\src\main\java\*.java
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at jdk.compiler/com.sun.tools.javac.main.Option$37.process(Option.java:693)
        at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Option.java:1088)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Arguments.java:381)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:347)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:193)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:229)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
********** BUILD FAILURE **********
```

**Comment by damithc** [comment]
There was a similar issue posted earlier https://github.com/nus-cs2103-AY2223S1/forum/issues/28
@ThomasHoooo how did you resolve your issue?

**Comment by ThomasHoooo** [comment]
Hi I visited your github and seems like your .java files in `\src\main\java\duke\` is dependent on the files in `\src\main\java\duke\task\`. Your situation is slightly different from mine but I can see how I can help.

Can you try `javac -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\duke\task\*.java ..\src\main\java\duke\*.java`?

If not, maybe try to separate into two lines?
```
javac -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\duke\task\*.java
javac -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\duke\*.java
```
