### ISSUE TITLE
Application crashed after running Launcher class

### ISSUE THREAD

**Issue by onepersonhere** [nus-cs2103-AY2223S1/forum#88]
Details:
* Intellij ver 2022.2.1 Ultimate Edition Build #IU-222.3739.54
* Using temurin-11 Eclipse version 11.0.15
* Windows 11

```java
// Under Launcher Class
public class Launcher {
    public static void main(String[] args) {
        Application.launch(Duke.class, args);
    }
}

//Under Duke Class
@Override
public void start(Stage stage) throws Exception {
    Label helloWorld = new Label("Hello World!"); // Creating a new Label control
    Scene scene = new Scene(helloWorld); // Setting the scene to be our Label

    stage.setScene(scene); // Setting the stage to show our screen
    stage.show(); // Render the stage.
}
```

Error stacktrace
```
Exception in Application constructor
Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class duke.Duke
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:890)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoSuchMethodException: duke.Duke.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
Caused by: java.lang.NoSuchMethodException: duke.Duke.<init>()

	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:801)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	... 1 more

Execution failed for task ':Launcher.main()'.
```

`Caused by: java.lang.NoSuchMethodException: duke.Duke.<init>()`

Anyone has any ideas?
I tried following past [solutions](https://github.com/nus-cs2103-AY1920S2/forum/issues/31) provided by hanming but did not resolve it.

**Comment by onepersonhere** [comment]
Solved it by providing a default constructor for Duke.
